import React, { useState } from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faChevronDown, faChevronUp } from '@fortawesome/free-solid-svg-icons'
import Typography from '@bit/mui-org.material-ui.typography'
import Accordion from '../../Accordion'
import Card from '../../Card'

const howMuch = (
  <>
    <p>
      CloudSolar will measure and record electricity generated by our expanding
      pool of solar panels. We have sites across Barbados and each of those
      sites will produce energy every day. We take the total energy produced
      monthly at each site (kWh) and divide by the total solar pool capacity
      installed (kWp). Each of our community solar panel owners will receive
      credits for their proportional share of the energy produced. The energy
      credits will be calculated using the current FIT rates and the credit will
      be paid out monthly into your Solar Credits Account. For example: In one
      month, the solar pool could generate 110 kWh per kWp installed. Each
      customer would receive their share of that multiplied by the FIT rate
      applicable to the solar panel capacity they have purchased. For example:
      If a customer owns 10 panels or 2.6 kWp (DC), to get their monthly solar
      credits you would multiply 2.6 kWp x 110 kWh x 42.75 cents = $122.27 less
      the CloudSolar maintenance fee (20%) for a net payment of $97.81. See FIT
      payment table below:
    </p>

    <div className="faq-table">
      <table>
        <thead>
          <tr>
            <td>Solar Purchased(kW AC)</td> <td>Rate as at Oct 1 2019</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1-10 kW</td> <td>$0.4275</td>
          </tr>
          <tr>
            <td>15-100 KW</td> <td>$0.4475</td>
          </tr>
          <tr>
            <td>101-250 KW</td> <td>$0.4175</td>
          </tr>
          <tr>
            <td>251-500 kW</td> <td>$0.3825</td>
          </tr>
          <tr>
            <td>501-1000 kW</td> <td>$0.3625</td>
          </tr>
        </tbody>
      </table>
    </div>
  </>
)

const content = [
  {
    question: 'What is CloudSolar?',
    answer: `CloudSolar is an online marketplace for digital solar panels. 
    We enable our clients to own solar panels in a community of solar installations, 
    while removing the barriers and hassles that entail owning a physically 
    installed Solar PV system. Our well-managed, sustainable and efficient solar 
    PV operations portfolio, generates solar energy that we pool together and sell 
    on behalf of our clients to the utility company. All of our PV farms are currently 
    operational and selling energy to the national grid. We enable our clients to own remotely installed solar panels 
    without the physical installation and operational hassles that 
    come along with installing a physical Solar PV system on your roof or land.
    
    CloudSolar is a special purpose company that was setup as a digital 
    community of solar installations that enables everyone, living anywhere to 
    own solar panels located remotely, without physically installing panels 
    on their own roof. Everything is administered online and earnings are pooled 
    together in our cloud platform to mitigate risk and non-performance of our solar sites.`,
  },
  {
    question:
      'What is the benefit of buying digital solar vs. traditional solar?',
    answer: `There are countless. One of the main factors that we like to tell persons
    is that you are getting the lowest costing solution for your solar panels because we buy
    straight from the manufacturer in bulk, install systems across Barbados
    and pass all savings directly on to our customers so that it is a win-win
    situation for both parties. Another key factor in buying digital solar panels
    is the absence of the roof or land space that a customer is required to own in order to participate.`,
  },
  {
    question: 'How do I earn money from my purchase?',
    answer: howMuch,
  },
  {
    question: 'Does the system work if there is an outage?',
    answer: `No. The inverter needs a power supply to convert generated electricity
    from DC to AC. Without a power supply the inverter will not work and the
    network will go offline. Since we are a pool of solar, when one system
    goes down, it will have minimal impact on the pool affording our customers
    “effectively no downtime”.`,
  },
  {
    question:
      'What happens at the end of my agreement/contract with CloudSolar?',
    answer: `CloudSolar has a maximum service contract length of 25 years (life-cycle of
        the solar panels). At the end of the 25 year term, the solar panels would have depreciated to 
        a value of zero and new panels would need to be installed in their place. Your income stops after this time period as CloudSolar will be 
        renegotiating its license agreements and replacing the old solar panels with new ones. Like with all
        solar products, once the end of life is reached the solar panels will need
        to be replaced and hence you will need to purchase a new panel/s to
        continue to enjoy the same energy production savings. The owner of the system
        will need to determine if they wish to install more solar panels on the licensed
        infrastructure of CloudSolar's solar asset network or if they would like to exit the agreement and sell the obsolete panels.`,
  },
]

export default function Questions() {
  const [activeEventKey, setActiveEventKey] = useState(0)

  return (
    <div className="">
      <Accordion activeEventKey={activeEventKey} onToggle={setActiveEventKey}>
        {content.map(({ question, answer }, index) => (
          <Card key={index}>
            <Accordion.Toggle element={Card.Header} eventKey={index}>
              <Typography variant="body1" style={{ marginTop: 5 }}>
                {question}
              </Typography>
              {activeEventKey !== index && (
                <span style={{ marginTop: 8 }}>
                  <FontAwesomeIcon icon={faChevronDown} className="qIcon" />
                </span>
              )}

              {activeEventKey === index && (
                <span style={{ marginTop: 8 }}>
                  <FontAwesomeIcon icon={faChevronUp} className="qIcon" />
                </span>
              )}
            </Accordion.Toggle>
            <Accordion.Collapse eventKey={index} element={Card.Body}>
              {answer}
            </Accordion.Collapse>
          </Card>
        ))}
      </Accordion>
    </div>
  )
}
